name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@master
        uses: actions/checkout@master

      - name: Enable corepack (allow to use pnpm)
        run: corepack enable

      - name: actions/setup-node@master
        uses: actions/setup-node@master
        with:
          node-version: 23

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Execute vitest tests
        run: pnpm test:unit
