name: release

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

jobs:
  release:
    if: ${{ github.event.head_commit.author.name != 'renovate[bot]' }}

    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Enable corepack (allow to use pnpm)
        run: corepack enable

      - name: Run actions/setup-node
        uses: actions/setup-node@master
        with:
          node-version: 23

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Initialize Git user
        run: |
          git config --global user.email "quentin.macq@outlook.fr"
          git config --global user.name "Release Workflow"

      - name: Run release
        run: pnpm release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}